App:
  Name: "go.micro.greeter"
  Env: "dev"
  RegisterTTL: 30
  RegisterInterval: 30
  Version: "1.0.0"
  Endpoint: "127.0.0.1:2379"
MySQL:
  Host: "xxxxxxxxxxx"
  Port: 33061
  DbName: "xxxxxxx"
  User: "xxxxxx"
  Pass: "xxxxx"
Redis:
  Host: "xxxxxxxxx"
  Port: 6379
  Password: ""
  DB: 0
NSQ:
  Topic: "test"
  Channel: "nsq_to_file"
  Addr: "xxxxxxxx:4161"